### ISSUE TITLE
Missing HARD_INITIAL_POSE in FloatingMiaGraspEnv

### ISSUE THREAD

**Issue by xkiixkii** [dfki-ric/deformable_gym#41]
In uniform_initialisation_example.py; Line: 16.
`base_initial_pose = FloatingMiaGraspEnv.HARD_INITIAL_POSE.copy()`
the initialpose is assigned HARD_INITIAL_POSE but there is no such const variable in FloatingMiaGraspEnv.

**Comment by mlaux1** [comment]
Thank you for pointing this out. The name of this constant was changed to INITIAL_POSE.
